# Web: http://bentopdf:8080

services:
    bentopdf:
        image: ghcr.io/alam00000/bentopdf-simple:latest
        container_name: bentopdf
        restart: always
        networks:
            - proxy-net
        labels:
            traefik.enable: true
            traefik.http.routers.pdf.entrypoints: web,websecure
            traefik.http.routers.pdf.tls: true
            traefik.http.routers.pdf.tls.certresolver: production
            traefik.http.routers.pdf.rule: Host(`pdf.example.com`)
            traefik.http.services.pdf.loadbalancer.server.port: 8080

networks:
    proxy-net:
        name: proxy-network
        external: true